[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "espar_lab"

[tool.pytest.ini_options]
testpaths = "esparlabctrl/tests"
markers = [
    "mock: mark a test as a test that uses a mock",
    "real_device: mark a test as a test that uses a real device",
]